import {
	NotePencilIcon,
	AlertCircleIcon,
	CalendarIcon,
	CarIcon,
	CarMultipleIcon,
	CheckIcon,
	CurrencyDollarIcon,
	MagnifyingGlassIcon,
	PhoneIcon,
	PlusIcon,
	StarIcon,
} from '@autoguru/icons';

export const argTypesExampleIcons = {
	options: [
		'None',
		'Car',
		'Phone',
		'Car Multiple',
		'Calendar',
		'Magnify',
		'Account Edit',
		'Alert Circle',
		'Currency USD',
		'Plus',
		'Star',
		'Check',
	],
	mapping: {
		None: null,
		Magnify: MagnifyingGlassIcon,
		Car: CarIcon,
		Phone: PhoneIcon,
		'Car Multiple': CarMultipleIcon,
		Calendar: CalendarIcon,
		'Account Edit': NotePencilIcon,
		'Alert Circle': AlertCircleIcon,
		'Currency USD': CurrencyDollarIcon,
		Plus: PlusIcon,
		Star: StarIcon,
		Check: CheckIcon,
	},
};
