extends:
    - 'plugin:@autoguru/base'
    - 'plugin:@autoguru/react'
    - 'plugin:@autoguru/jest'
    - 'plugin:@autoguru/typescript'
    - 'plugin:storybook/recommended'

env:
    jest: true
    node: true
    browser: true

rules:
    sonarjs/cognitive-complexity: warn
    sonarjs/no-nested-switch: off
    unicorn/prefer-global-this: warn
    '@typescript-eslint/no-unused-vars': warn
    '@typescript-eslint/no-unnecessary-type-constraint': warn
