const { TreatPlugin } = require('treat/webpack-plugin');
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const { join } = require('path');

const ourCodeFiles = [
	join(__dirname, './packages/'),
	join(__dirname, './.playroom/'),
	/@autoguru\/.*/,
];

module.exports = {
	title: 'Overdrive',
	components: './.playroom/components.ts',
	outputPath: './.playroom/dist/',
	frameComponent: './.playroom/frame.tsx',
	themes: './packages/overdrive/lib/themes/index.ts',
	widths: [320, 768, 1024, 1500],
	paramType: 'search',
	baseUrl: '/playroom/',
	port: 6007,
	openBrowser: true,
	webpackConfig: () => ({
		module: {
			rules: [
				{
					test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
					use: [
						MiniCssExtractPlugin.loader,
						{
							loader: require.resolve('css-loader'),
							options: {
								url: true, // Required as image imports should be handled via JS/TS import statements
							},
						},
					],
				},
				{
					test: /\.css$/,
					include: ourCodeFiles,
					use: [
						{
							loader: require.resolve('style-loader'),
						},
						{
							loader: require.resolve('css-loader'),
						},
					],
				},
				{
					test: /\.tsx?$/,
					include: ourCodeFiles,
					use: [
						{
							loader: require.resolve('ts-loader'),
							options: {
								configFile: require.resolve(
									'./packages/overdrive/tsconfig.json',
								),
								transpileOnly: true,
							},
						},
					],
				},
			],
		},
		plugins: [
			new VanillaExtractPlugin(),
			new MiniCssExtractPlugin(),
			new TreatPlugin({
				outputLoaders: [
					{
						loader: require.resolve('style-loader'),
						options: {
							attributes: {
								treat: true,
							},
						},
					},
				],
			}),
		],
		resolve: {
			extensions: ['.tsx', '.ts', '.js', '.mjs', '.json'],
		},
	}),
};
