/* eslint-disable sonarjs/no-duplicate-string -- flat data lookup table */
// Maps every @autoguru/icons export to a category.
// Categories mirror the AutoGuru Design System 2026 Figma "Icon set"
// (Phosphor 2.1 taxonomy + AutoGuru bespoke groups).
// "Filled" holds the filled-weight icons (export name ends in "Filled").
// Regenerate when the @autoguru/icons package changes.

/** Display order of icon categories in the Icon Set story. */
export const iconCategoryOrder = [
	"AutoGuru",
	"Brands",
	"Filled",
	"Arrows",
	"Commerce",
	"Communication",
	"Design",
	"Development",
	"Education",
	"Games",
	"Maps & Travel",
	"Math & Finance",
	"Media",
	"Office & Editing",
	"People",
	"Security & Warnings",
	"System & Devices",
	"Time",
	"Weather & Nature",
] as const;

export type IconCategory = (typeof iconCategoryOrder)[number];

/** Icon export name -> category. */
export const iconCategory: Record<string, IconCategory> = {
	AfterpayFilledIcon: "Filled",
	AfterpayIcon: "Brands",
	AirConditionerIcon: "AutoGuru",
	AlertCircleIcon: "Security & Warnings",
	ArrowBendUpLeftIcon: "Arrows",
	ArrowClockwiseIcon: "Arrows",
	ArrowCounterClockwiseIcon: "Arrows",
	ArrowDownIcon: "Arrows",
	ArrowLeftIcon: "Arrows",
	ArrowRightIcon: "Arrows",
	ArrowsClockwiseIcon: "Arrows",
	ArrowsDownUpIcon: "Arrows",
	ArrowsInIcon: "Arrows",
	ArrowsOutIcon: "Arrows",
	ArrowSquareOutIcon: "Arrows",
	ArrowUpIcon: "Arrows",
	BatteryChargingIcon: "System & Devices",
	BatteryFullIcon: "System & Devices",
	BnplNewIcon: "Commerce",
	BooksIcon: "Education",
	BrakesIcon: "AutoGuru",
	BroomIcon: "Commerce",
	CalendarIcon: "Time",
	CalendarPlusIcon: "Time",
	CalendarXIcon: "Time",
	CaretDownIcon: "Arrows",
	CaretLeftIcon: "Arrows",
	CaretRightIcon: "Arrows",
	CaretUpIcon: "Arrows",
	CarIcon: "Maps & Travel",
	CarLiftedPickupIcon: "AutoGuru",
	CarMultipleIcon: "AutoGuru",
	CarProfileIcon: "Maps & Travel",
	CarSeatIcon: "AutoGuru",
	CarSimpleIcon: "Maps & Travel",
	CarTireAlertIcon: "AutoGuru",
	CarTractionControlIcon: "AutoGuru",
	CarWindshieldIcon: "AutoGuru",
	ChartDonutIcon: "Math & Finance",
	ChartPieIcon: "Math & Finance",
	ChatDotsIcon: "Communication",
	CheckCircleIcon: "System & Devices",
	CheckIcon: "System & Devices",
	ChecksIcon: "System & Devices",
	ClipboardCheckIcon: "AutoGuru",
	ClipboardFleetOutlineIcon: "AutoGuru",
	ClipboardTextIcon: "Office & Editing",
	ClockIcon: "Time",
	CloseCircleIcon: "System & Devices",
	CloudArrowUpIcon: "System & Devices",
	CoffeeIcon: "Commerce",
	CoinIcon: "Commerce",
	CopyIcon: "Office & Editing",
	CreditCardIcon: "Commerce",
	CreditCardWirelessIcon: "Commerce",
	CurrencyCircleDollarIcon: "Commerce",
	CurrencyDollarIcon: "Commerce",
	CurrencyOffIcon: "Math & Finance",
	DatabaseIcon: "Development",
	DealershipIcon: "AutoGuru",
	DeviceMobileIcon: "System & Devices",
	DiamondIcon: "Games",
	DiamondsFourIcon: "Design",
	DieselIcon: "AutoGuru",
	DotsThreeIcon: "System & Devices",
	DownloadIcon: "System & Devices",
	DumpTruckIcon: "AutoGuru",
	EngineIcon: "AutoGuru",
	EngineOffIcon: "AutoGuru",
	EnvelopeIcon: "Communication",
	EvHybridIcon: "AutoGuru",
	ExclamationMarkIcon: "Security & Warnings",
	EyeSlashIcon: "Design",
	FacebookBoxIcon: "Brands",
	FadersHorizontalIcon: "Media",
	FanIcon: "Commerce",
	FgPlateIcon: "AutoGuru",
	FileTextIcon: "Office & Editing",
	FireIcon: "Weather & Nature",
	FlagIcon: "Maps & Travel",
	FloppyDiskIcon: "Office & Editing",
	FolderLockIcon: "Office & Editing",
	FolderOpenIcon: "Office & Editing",
	ForkliftIcon: "AutoGuru",
	FourByFourIcon: "AutoGuru",
	FunnelIcon: "Office & Editing",
	GaugeIcon: "System & Devices",
	GearIcon: "System & Devices",
	GearSixIcon: "System & Devices",
	GlobeIcon: "Maps & Travel",
	GolfCartIcon: "AutoGuru",
	GraduationCapIcon: "Education",
	GridFourIcon: "Design",
	HashIcon: "Communication",
	HeartFilledIcon: "Filled",
	HouseIcon: "Maps & Travel",
	IdentificationBadgeIcon: "People",
	IdentificationCardIcon: "People",
	InfinityIcon: "Math & Finance",
	InfoIcon: "Security & Warnings",
	InformationIcon: "Security & Warnings",
	InstagramFilledIcon: "Filled",
	InstagramIcon: "Brands",
	KeyIcon: "Security & Warnings",
	LearnerIcon: "AutoGuru",
	LightbulbIcon: "System & Devices",
	LightningIcon: "System & Devices",
	LinkedinBoxIcon: "Brands",
	ListChecksIcon: "Office & Editing",
	ListIcon: "Office & Editing",
	LockIcon: "Security & Warnings",
	LpgIcon: "AutoGuru",
	MagicWandIcon: "Design",
	MagnifyingGlassIcon: "System & Devices",
	MapPinIcon: "Maps & Travel",
	MapPinLineIcon: "Maps & Travel",
	MapTrifoldIcon: "Maps & Travel",
	MaskHappyIcon: "Games",
	MicrophoneIcon: "Media",
	MinusCircleIcon: "Math & Finance",
	MinusIcon: "Math & Finance",
	MobileMechanicIcon: "AutoGuru",
	MoneyIcon: "Commerce",
	MotorcycleIcon: "Maps & Travel",
	MufflerIcon: "AutoGuru",
	NotePencilIcon: "Office & Editing",
	OttoIcon: "AutoGuru",
	PackageIcon: "Commerce",
	PaperPlaneTiltIcon: "Communication",
	ParkingIcon: "AutoGuru",
	PauseIcon: "Media",
	PencilSimpleLineIcon: "Design",
	PercentIcon: "Math & Finance",
	PhoneCallIcon: "Communication",
	PhoneIcon: "Communication",
	PlantIcon: "Weather & Nature",
	PlateIcon: "AutoGuru",
	PlayIcon: "Media",
	PlugsConnectedIcon: "System & Devices",
	PlusCircleIcon: "Math & Finance",
	PlusIcon: "Math & Finance",
	PowerIcon: "System & Devices",
	PPlateIcon: "AutoGuru",
	QuestionIcon: "Security & Warnings",
	QuoteRequestIcon: "AutoGuru",
	RadioButtonIcon: "System & Devices",
	RssIcon: "Communication",
	RulerIcon: "Design",
	SeatIcon: "Maps & Travel",
	ShieldCheckIcon: "Security & Warnings",
	ShoppingCartIcon: "Commerce",
	SignInIcon: "System & Devices",
	SignOutIcon: "System & Devices",
	SignpostIcon: "Maps & Travel",
	SlidersIcon: "Media",
	SmileyIcon: "People",
	SortAscendingIcon: "Office & Editing",
	SparkleIcon: "Weather & Nature",
	StarHalfIcon: "Communication",
	StarIcon: "Communication",
	StorefrontIcon: "Commerce",
	SuspensionIcon: "AutoGuru",
	TagIcon: "Commerce",
	TiktokFilledIcon: "Filled",
	TiktokIcon: "Brands",
	ToolboxIcon: "Commerce",
	TowTruckIcon: "AutoGuru",
	TractorIcon: "Commerce",
	TransmissionIcon: "AutoGuru",
	TrashIcon: "Office & Editing",
	TrayArrowUpIcon: "Office & Editing",
	TrophyIcon: "Games",
	TruckFastIcon: "AutoGuru",
	TruckIcon: "Maps & Travel",
	TruckTrailerIcon: "Commerce",
	TyreIcon: "AutoGuru",
	TyreTreadIcon: "AutoGuru",
	UberBoxIcon: "Brands",
	UberBoxWhiteIcon: "Brands",
	UberIcon: "Brands",
	UserCircleCheckIcon: "People",
	UserCircleIcon: "People",
	UserCircleMinusIcon: "People",
	UserFocusIcon: "People",
	UserIcon: "People",
	UserSquareIcon: "People",
	VanIcon: "Maps & Travel",
	VinylRecordIcon: "Media",
	WalletIcon: "Commerce",
	WarningCircleIcon: "Security & Warnings",
	WarningDiamondIcon: "Security & Warnings",
	WarningIcon: "Security & Warnings",
	WifiHighIcon: "System & Devices",
	WifiSlashIcon: "System & Devices",
	WorkshopIcon: "AutoGuru",
	WrenchIcon: "Commerce",
	XIcon: "System & Devices",
	XSocialFilledIcon: "Filled",
	XSocialIcon: "Brands",
	XSquareIcon: "Math & Finance",
	YoutubeFilledIcon: "Filled",
	YoutubeIcon: "Brands",
};
