/* eslint-disable sonarjs/no-duplicate-string, sonarjs/no-hardcoded-passwords -- flat icon-name data lookup table */
// Maps every @autoguru/icons export to a category.
// Categories mirror the AutoGuru Design System 2026 Figma "Icon set"
// (Phosphor 2.1 taxonomy + AutoGuru bespoke groups).
// "Filled" holds the filled-weight icons (export name ends in "Filled").
// Regenerate when the @autoguru/icons package changes.

/** Display order of icon categories in the Icon Set story. */
export const iconCategoryOrder = [
	"AutoGuru",
	"Brands",
	"Filled",
	"Arrows",
	"Commerce",
	"Communication",
	"Design",
	"Development",
	"Education",
	"Games",
	"Health & Wellness",
	"Maps & Travel",
	"Math & Finance",
	"Media",
	"Office & Editing",
	"People",
	"Security & Warnings",
	"System & Devices",
	"Time",
	"Weather & Nature",
] as const;

export type IconCategory = (typeof iconCategoryOrder)[number];

/** Icon export name -> category. */
export const iconCategory: Record<string, IconCategory> = {
	AcornIcon: "Weather & Nature",
	AddressBookIcon: "Communication",
	AddressBookTabsIcon: "Communication",
	AfterpayFilledIcon: "Filled",
	AfterpayIcon: "Brands",
	AirConditionerIcon: "AutoGuru",
	AirplaneIcon: "Maps & Travel",
	AirplaneInFlightIcon: "Maps & Travel",
	AirplaneLandingIcon: "Maps & Travel",
	AirplaneTakeoffIcon: "Maps & Travel",
	AirplaneTaxiingIcon: "Maps & Travel",
	AirplaneTiltIcon: "Maps & Travel",
	AirplayIcon: "Media",
	AirTrafficControlIcon: "Maps & Travel",
	AlarmIcon: "Time",
	AlertCircleIcon: "Filled",
	AlienIcon: "Games",
	AlignBottomIcon: "Design",
	AlignBottomSimpleIcon: "Design",
	AlignCenterHorizontalIcon: "Design",
	AlignCenterHorizontalSimpleIcon: "Design",
	AlignCenterVerticalIcon: "Design",
	AlignCenterVerticalSimpleIcon: "Design",
	AlignLeftIcon: "Design",
	AlignLeftSimpleIcon: "Design",
	AlignRightIcon: "Design",
	AlignRightSimpleIcon: "Design",
	AlignTopIcon: "Design",
	AlignTopSimpleIcon: "Design",
	AmazonLogoIcon: "Brands",
	AmbulanceIcon: "Health & Wellness",
	AnchorIcon: "Maps & Travel",
	AnchorSimpleIcon: "Maps & Travel",
	AndroidLogoIcon: "Brands",
	AngleIcon: "Design",
	AngularLogoIcon: "Brands",
	ApertureIcon: "Media",
	AppleLogoIcon: "Brands",
	ApplePodcastsLogoIcon: "Brands",
	ApproximateEqualsIcon: "Math & Finance",
	AppStoreLogoIcon: "Brands",
	AppWindowIcon: "System & Devices",
	ArchiveIcon: "Office & Editing",
	ArmchairIcon: "Commerce",
	ArrowArcLeftIcon: "Arrows",
	ArrowArcRightIcon: "Arrows",
	ArrowBendDoubleUpLeftIcon: "Arrows",
	ArrowBendDoubleUpRightIcon: "Arrows",
	ArrowBendDownLeftIcon: "Arrows",
	ArrowBendDownRightIcon: "Arrows",
	ArrowBendLeftDownIcon: "Arrows",
	ArrowBendLeftUpIcon: "Arrows",
	ArrowBendRightDownIcon: "Arrows",
	ArrowBendRightUpIcon: "Arrows",
	ArrowBendUpLeftIcon: "Arrows",
	ArrowBendUpRightIcon: "Arrows",
	ArrowCircleDownIcon: "Arrows",
	ArrowCircleDownLeftIcon: "Arrows",
	ArrowCircleDownRightIcon: "Arrows",
	ArrowCircleLeftIcon: "Arrows",
	ArrowCircleRightIcon: "Arrows",
	ArrowCircleUpIcon: "Arrows",
	ArrowCircleUpLeftIcon: "Arrows",
	ArrowCircleUpRightIcon: "Arrows",
	ArrowClockwiseIcon: "Arrows",
	ArrowCounterClockwiseIcon: "Arrows",
	ArrowDownIcon: "Arrows",
	ArrowDownLeftIcon: "Arrows",
	ArrowDownRightIcon: "Arrows",
	ArrowElbowDownLeftIcon: "Arrows",
	ArrowElbowDownRightIcon: "Arrows",
	ArrowElbowLeftDownIcon: "Arrows",
	ArrowElbowLeftIcon: "Arrows",
	ArrowElbowLeftUpIcon: "Arrows",
	ArrowElbowRightDownIcon: "Arrows",
	ArrowElbowRightIcon: "Arrows",
	ArrowElbowRightUpIcon: "Arrows",
	ArrowElbowUpLeftIcon: "Arrows",
	ArrowElbowUpRightIcon: "Arrows",
	ArrowFatDownIcon: "Arrows",
	ArrowFatLeftIcon: "Arrows",
	ArrowFatLineDownIcon: "Arrows",
	ArrowFatLineLeftIcon: "Arrows",
	ArrowFatLineRightIcon: "Arrows",
	ArrowFatLinesDownIcon: "Arrows",
	ArrowFatLinesLeftIcon: "Arrows",
	ArrowFatLinesRightIcon: "Arrows",
	ArrowFatLinesUpIcon: "Arrows",
	ArrowFatLineUpIcon: "Arrows",
	ArrowFatRightIcon: "Arrows",
	ArrowFatUpIcon: "Arrows",
	ArrowLeftIcon: "Arrows",
	ArrowLineDownIcon: "Arrows",
	ArrowLineDownLeftIcon: "Arrows",
	ArrowLineDownRightIcon: "Arrows",
	ArrowLineLeftIcon: "Arrows",
	ArrowLineRightIcon: "Arrows",
	ArrowLineUpIcon: "Arrows",
	ArrowLineUpLeftIcon: "Arrows",
	ArrowLineUpRightIcon: "Arrows",
	ArrowRightIcon: "Arrows",
	ArrowsClockwiseIcon: "Arrows",
	ArrowsCounterClockwiseIcon: "Arrows",
	ArrowsDownUpIcon: "Arrows",
	ArrowsHorizontalIcon: "Arrows",
	ArrowsInCardinalIcon: "Arrows",
	ArrowsInIcon: "Arrows",
	ArrowsInLineHorizontalIcon: "Arrows",
	ArrowsInLineVerticalIcon: "Arrows",
	ArrowsInSimpleIcon: "Arrows",
	ArrowsLeftRightIcon: "Arrows",
	ArrowsMergeIcon: "Arrows",
	ArrowsOutCardinalIcon: "Arrows",
	ArrowsOutIcon: "Arrows",
	ArrowsOutLineHorizontalIcon: "Arrows",
	ArrowsOutLineVerticalIcon: "Arrows",
	ArrowsOutSimpleIcon: "Arrows",
	ArrowSquareDownIcon: "Arrows",
	ArrowSquareDownLeftIcon: "Arrows",
	ArrowSquareDownRightIcon: "Arrows",
	ArrowSquareInIcon: "Arrows",
	ArrowSquareLeftIcon: "Arrows",
	ArrowSquareOutIcon: "Arrows",
	ArrowSquareRightIcon: "Arrows",
	ArrowSquareUpIcon: "Arrows",
	ArrowSquareUpLeftIcon: "Arrows",
	ArrowSquareUpRightIcon: "Arrows",
	ArrowsSplitIcon: "Arrows",
	ArrowsVerticalIcon: "Arrows",
	ArrowUDownLeftIcon: "Arrows",
	ArrowUDownRightIcon: "Arrows",
	ArrowULeftDownIcon: "Arrows",
	ArrowULeftUpIcon: "Arrows",
	ArrowUpIcon: "Arrows",
	ArrowUpLeftIcon: "Arrows",
	ArrowUpRightIcon: "Arrows",
	ArrowURightDownIcon: "Arrows",
	ArrowURightUpIcon: "Arrows",
	ArrowUUpLeftIcon: "Arrows",
	ArrowUUpRightIcon: "Arrows",
	ArticleIcon: "Media",
	ArticleMediumIcon: "Media",
	ArticleNyTimesIcon: "Media",
	AsclepiusIcon: "Health & Wellness",
	AsteriskIcon: "Communication",
	AsteriskSimpleIcon: "Communication",
	AtIcon: "Communication",
	AtomIcon: "Weather & Nature",
	AvocadoIcon: "Commerce",
	AxeIcon: "Commerce",
	BabyCarriageIcon: "Commerce",
	BabyIcon: "People",
	BackpackIcon: "Commerce",
	BackspaceIcon: "System & Devices",
	BagIcon: "Commerce",
	BagSimpleIcon: "Commerce",
	BalloonIcon: "Commerce",
	BandaidsIcon: "Health & Wellness",
	BankIcon: "Math & Finance",
	BarbellIcon: "Health & Wellness",
	BarcodeIcon: "Commerce",
	BarnIcon: "Commerce",
	BarricadeIcon: "Maps & Travel",
	BaseballCapIcon: "Commerce",
	BaseballHelmetIcon: "Games",
	BaseballIcon: "Games",
	BasketballIcon: "Games",
	BasketIcon: "Commerce",
	BathtubIcon: "Commerce",
	BatteryChargingIcon: "System & Devices",
	BatteryChargingVerticalIcon: "System & Devices",
	BatteryEmptyIcon: "System & Devices",
	BatteryFullIcon: "System & Devices",
	BatteryHighIcon: "System & Devices",
	BatteryLowIcon: "System & Devices",
	BatteryMediumIcon: "System & Devices",
	BatteryPlusIcon: "System & Devices",
	BatteryPlusVerticalIcon: "System & Devices",
	BatteryVerticalEmptyIcon: "System & Devices",
	BatteryVerticalFullIcon: "System & Devices",
	BatteryVerticalHighIcon: "System & Devices",
	BatteryVerticalLowIcon: "System & Devices",
	BatteryVerticalMediumIcon: "System & Devices",
	BatteryWarningIcon: "System & Devices",
	BatteryWarningVerticalIcon: "System & Devices",
	BeachBallIcon: "Games",
	BeanieIcon: "Commerce",
	BedIcon: "Health & Wellness",
	BeerBottleIcon: "Commerce",
	BeerSteinIcon: "Commerce",
	BehanceLogoIcon: "Brands",
	BellIcon: "System & Devices",
	BellRingingIcon: "System & Devices",
	BellSimpleIcon: "System & Devices",
	BellSimpleRingingIcon: "System & Devices",
	BellSimpleSlashIcon: "System & Devices",
	BellSimpleZIcon: "System & Devices",
	BellSlashIcon: "System & Devices",
	BellZIcon: "System & Devices",
	BeltIcon: "Commerce",
	BezierCurveIcon: "Design",
	BicycleIcon: "Maps & Travel",
	BinaryIcon: "Development",
	BinocularsIcon: "Commerce",
	BiohazardIcon: "Security & Warnings",
	BirdIcon: "Weather & Nature",
	BlueprintIcon: "Design",
	BluetoothConnectedIcon: "System & Devices",
	BluetoothIcon: "System & Devices",
	BluetoothSlashIcon: "System & Devices",
	BluetoothXIcon: "System & Devices",
	BnplNewIcon: "AutoGuru",
	BoatIcon: "Maps & Travel",
	BombIcon: "Games",
	BoneIcon: "Weather & Nature",
	BookBookmarkIcon: "Education",
	BookIcon: "Education",
	BookmarkIcon: "Education",
	BookmarksIcon: "Education",
	BookmarkSimpleIcon: "Education",
	BookmarksSimpleIcon: "Education",
	BookOpenIcon: "Education",
	BookOpenTextIcon: "Education",
	BookOpenUserIcon: "Education",
	BooksIcon: "Education",
	BootIcon: "Commerce",
	BoulesIcon: "Games",
	BoundingBoxIcon: "Design",
	BowlFoodIcon: "Commerce",
	BowlingBallIcon: "Games",
	BowlSteamIcon: "Commerce",
	BoxArrowDownIcon: "Office & Editing",
	BoxArrowUpIcon: "Office & Editing",
	BoxingGloveIcon: "Games",
	BracketsAngleIcon: "Development",
	BracketsCurlyIcon: "Development",
	BracketsRoundIcon: "Development",
	BracketsSquareIcon: "Development",
	BrainIcon: "Health & Wellness",
	BrakesIcon: "AutoGuru",
	BrandyIcon: "Commerce",
	BreadIcon: "Commerce",
	BridgeIcon: "Commerce",
	BriefcaseIcon: "Office & Editing",
	BriefcaseMetalIcon: "Office & Editing",
	BroadcastIcon: "Communication",
	BroomIcon: "Commerce",
	BrowserIcon: "System & Devices",
	BrowsersIcon: "System & Devices",
	BugBeetleIcon: "Development",
	BugDroidIcon: "Development",
	BugIcon: "Development",
	BuildingApartmentIcon: "Commerce",
	BuildingIcon: "Commerce",
	BuildingOfficeIcon: "Commerce",
	BuildingsIcon: "Commerce",
	BulldozerIcon: "Commerce",
	BusIcon: "Maps & Travel",
	ButterflyIcon: "Weather & Nature",
	CableCarIcon: "Maps & Travel",
	CactusIcon: "Weather & Nature",
	CakeIcon: "Commerce",
	CalculatorIcon: "Math & Finance",
	CalendarBlankIcon: "Time",
	CalendarCheckIcon: "Time",
	CalendarDotIcon: "Time",
	CalendarDotsIcon: "Time",
	CalendarHeartIcon: "Time",
	CalendarIcon: "Time",
	CalendarMinusIcon: "Time",
	CalendarPlusIcon: "Time",
	CalendarSlashIcon: "Time",
	CalendarStarIcon: "Time",
	CalendarXIcon: "Time",
	CallBellIcon: "Commerce",
	CameraIcon: "Media",
	CameraPlusIcon: "Media",
	CameraRotateIcon: "Media",
	CameraSlashIcon: "Media",
	CampfireIcon: "Weather & Nature",
	CarAlertIcon: "AutoGuru",
	CarBatteryIcon: "Commerce",
	CardholderIcon: "Commerce",
	CardsIcon: "Office & Editing",
	CardsThreeIcon: "Office & Editing",
	CaretCircleDoubleDownIcon: "Arrows",
	CaretCircleDoubleLeftIcon: "Arrows",
	CaretCircleDoubleRightIcon: "Arrows",
	CaretCircleDoubleUpIcon: "Arrows",
	CaretCircleDownIcon: "Arrows",
	CaretCircleLeftIcon: "Arrows",
	CaretCircleRightIcon: "Arrows",
	CaretCircleUpDownIcon: "Arrows",
	CaretCircleUpIcon: "Arrows",
	CaretDoubleDownIcon: "Arrows",
	CaretDoubleLeftIcon: "Arrows",
	CaretDoubleRightIcon: "Arrows",
	CaretDoubleUpIcon: "Arrows",
	CaretDownIcon: "Arrows",
	CaretLeftIcon: "Arrows",
	CaretLineDownIcon: "Arrows",
	CaretLineLeftIcon: "Arrows",
	CaretLineRightIcon: "Arrows",
	CaretLineUpIcon: "Arrows",
	CaretRightIcon: "Arrows",
	CaretUpDownIcon: "Arrows",
	CaretUpIcon: "Arrows",
	CarIcon: "Maps & Travel",
	CarInfoIcon: "AutoGuru",
	CarKeyIcon: "AutoGuru",
	CarLiftedPickupIcon: "AutoGuru",
	CarMultipleIcon: "AutoGuru",
	CarProfileIcon: "Maps & Travel",
	CarrotIcon: "Commerce",
	CarSeatIcon: "AutoGuru",
	CarSimpleIcon: "Maps & Travel",
	CarTireAlertIcon: "AutoGuru",
	CarTractionControlIcon: "AutoGuru",
	CarWindshieldIcon: "AutoGuru",
	CarWrenchIcon: "AutoGuru",
	CashRegisterIcon: "Commerce",
	CassetteTapeIcon: "Media",
	CastleTurretIcon: "Games",
	CatIcon: "Weather & Nature",
	CellSignalFullIcon: "System & Devices",
	CellSignalHighIcon: "System & Devices",
	CellSignalLowIcon: "System & Devices",
	CellSignalMediumIcon: "System & Devices",
	CellSignalNoneIcon: "System & Devices",
	CellSignalSlashIcon: "System & Devices",
	CellSignalXIcon: "System & Devices",
	CellTowerIcon: "Communication",
	CertificateIcon: "Education",
	ChairIcon: "Commerce",
	ChalkboardIcon: "Education",
	ChalkboardSimpleIcon: "Education",
	ChalkboardTeacherIcon: "Education",
	ChampagneIcon: "Commerce",
	ChargingStationIcon: "Maps & Travel",
	ChartBarHorizontalIcon: "Math & Finance",
	ChartBarIcon: "Math & Finance",
	ChartDonutIcon: "Math & Finance",
	ChartLineDownIcon: "Math & Finance",
	ChartLineIcon: "Math & Finance",
	ChartLineUpIcon: "Math & Finance",
	ChartPieIcon: "Math & Finance",
	ChartPieSliceIcon: "Math & Finance",
	ChartPolarIcon: "Math & Finance",
	ChartScatterIcon: "Math & Finance",
	ChatCenteredDotsIcon: "Communication",
	ChatCenteredIcon: "Communication",
	ChatCenteredSlashIcon: "Communication",
	ChatCenteredTextIcon: "Communication",
	ChatCircleDotsIcon: "Communication",
	ChatCircleIcon: "Communication",
	ChatCircleSlashIcon: "Communication",
	ChatCircleTextIcon: "Communication",
	ChatDotsIcon: "Communication",
	ChatIcon: "Communication",
	ChatsCircleIcon: "Communication",
	ChatsIcon: "Communication",
	ChatSlashIcon: "Communication",
	ChatsTeardropIcon: "Communication",
	ChatTeardropDotsIcon: "Communication",
	ChatTeardropIcon: "Communication",
	ChatTeardropSlashIcon: "Communication",
	ChatTeardropTextIcon: "Communication",
	ChatTextIcon: "Communication",
	CheckCircleIcon: "Filled",
	CheckerboardIcon: "Games",
	CheckFatIcon: "System & Devices",
	CheckIcon: "System & Devices",
	ChecksIcon: "System & Devices",
	CheckSquareIcon: "System & Devices",
	CheckSquareOffsetIcon: "System & Devices",
	CheersIcon: "Commerce",
	CheeseIcon: "Commerce",
	ChefHatIcon: "Commerce",
	CherriesIcon: "Commerce",
	ChurchIcon: "Maps & Travel",
	CigaretteIcon: "Commerce",
	CigaretteSlashIcon: "Commerce",
	CircleDashedIcon: "Design",
	CircleHalfIcon: "Design",
	CircleHalfTiltIcon: "Design",
	CircleIcon: "Design",
	CircleNotchIcon: "Design",
	CirclesFourIcon: "Design",
	CirclesThreeIcon: "Design",
	CirclesThreePlusIcon: "Design",
	CircuitryIcon: "System & Devices",
	CityIcon: "Commerce",
	ClipboardCheckIcon: "AutoGuru",
	ClipboardFleetOutlineIcon: "AutoGuru",
	ClipboardIcon: "Office & Editing",
	ClipboardTextIcon: "Office & Editing",
	ClockAfternoonIcon: "Time",
	ClockClockwiseIcon: "Time",
	ClockCountdownIcon: "Time",
	ClockCounterClockwiseIcon: "Time",
	ClockIcon: "Time",
	ClockUserIcon: "Time",
	CloseCircleIcon: "Filled",
	ClosedCaptioningIcon: "Media",
	CloudArrowDownIcon: "System & Devices",
	CloudArrowUpIcon: "System & Devices",
	CloudCheckIcon: "System & Devices",
	CloudFogIcon: "Weather & Nature",
	CloudIcon: "Weather & Nature",
	CloudLightningIcon: "Weather & Nature",
	CloudMoonIcon: "Weather & Nature",
	CloudRainIcon: "Weather & Nature",
	CloudSlashIcon: "System & Devices",
	CloudSnowIcon: "Weather & Nature",
	CloudSunIcon: "Weather & Nature",
	CloudWarningIcon: "System & Devices",
	CloudXIcon: "System & Devices",
	CloverIcon: "Weather & Nature",
	ClubIcon: "Games",
	ClutchIcon: "AutoGuru",
	CoatHangerIcon: "Commerce",
	CodaLogoIcon: "Brands",
	CodeBlockIcon: "Development",
	CodeIcon: "Development",
	CodepenLogoIcon: "Brands",
	CodesandboxLogoIcon: "Brands",
	CodeSimpleIcon: "Development",
	CoffeeBeanIcon: "Commerce",
	CoffeeIcon: "Commerce",
	CoinIcon: "Commerce",
	CoinsIcon: "Commerce",
	CoinVerticalIcon: "Commerce",
	ColumnsIcon: "Design",
	ColumnsPlusLeftIcon: "Design",
	ColumnsPlusRightIcon: "Design",
	CommandIcon: "System & Devices",
	CompassIcon: "Maps & Travel",
	CompassRoseIcon: "Maps & Travel",
	CompassToolIcon: "Design",
	ComputerTowerIcon: "System & Devices",
	ConfettiIcon: "Games",
	ContactlessPaymentIcon: "Commerce",
	ControlIcon: "System & Devices",
	CookieIcon: "Commerce",
	CookingPotIcon: "Commerce",
	CopyIcon: "Office & Editing",
	CopyleftIcon: "Media",
	CopyrightIcon: "Media",
	CopySimpleIcon: "Office & Editing",
	CornersInIcon: "Media",
	CornersOutIcon: "Media",
	CouchIcon: "Commerce",
	CourtBasketballIcon: "Games",
	CowboyHatIcon: "Commerce",
	CowIcon: "Weather & Nature",
	CpuIcon: "Development",
	CraneIcon: "Commerce",
	CraneTowerIcon: "Commerce",
	CreditCardIcon: "Commerce",
	CreditCardWirelessIcon: "AutoGuru",
	CricketIcon: "Games",
	CropIcon: "Design",
	CrosshairIcon: "Maps & Travel",
	CrosshairSimpleIcon: "Maps & Travel",
	CrossIcon: "Communication",
	CrownCrossIcon: "Games",
	CrownIcon: "Games",
	CrownSimpleIcon: "Games",
	CubeFocusIcon: "Games",
	CubeIcon: "Design",
	CubeTransparentIcon: "Design",
	CurrencyBtcIcon: "Commerce",
	CurrencyCircleDollarIcon: "Commerce",
	CurrencyCnyIcon: "Commerce",
	CurrencyDollarIcon: "Commerce",
	CurrencyDollarSimpleIcon: "Commerce",
	CurrencyEthIcon: "Commerce",
	CurrencyEurIcon: "Commerce",
	CurrencyGbpIcon: "Commerce",
	CurrencyInrIcon: "Commerce",
	CurrencyJpyIcon: "Commerce",
	CurrencyKrwIcon: "Commerce",
	CurrencyKztIcon: "Commerce",
	CurrencyNgnIcon: "Commerce",
	CurrencyOffIcon: "AutoGuru",
	CurrencyRubIcon: "Commerce",
	CursorClickIcon: "System & Devices",
	CursorIcon: "System & Devices",
	CursorTextIcon: "Office & Editing",
	CylinderIcon: "Design",
	DatabaseIcon: "Development",
	DealershipIcon: "AutoGuru",
	DeskIcon: "Commerce",
	DesktopIcon: "System & Devices",
	DesktopTowerIcon: "System & Devices",
	DetectiveIcon: "Security & Warnings",
	DeviceMobileCameraIcon: "System & Devices",
	DeviceMobileIcon: "System & Devices",
	DeviceMobileSlashIcon: "System & Devices",
	DeviceMobileSpeakerIcon: "System & Devices",
	DeviceRotateIcon: "System & Devices",
	DevicesIcon: "System & Devices",
	DeviceTabletCameraIcon: "System & Devices",
	DeviceTabletIcon: "System & Devices",
	DeviceTabletSpeakerIcon: "System & Devices",
	DevToLogoIcon: "Brands",
	DiamondIcon: "Games",
	DiamondsFourIcon: "Design",
	DiceFiveIcon: "Games",
	DiceFourIcon: "Games",
	DiceOneIcon: "Games",
	DiceSixIcon: "Games",
	DiceThreeIcon: "Games",
	DiceTwoIcon: "Games",
	DieselIcon: "AutoGuru",
	DiscIcon: "Media",
	DiscoBallIcon: "Games",
	DiscordLogoIcon: "Brands",
	DivideIcon: "Math & Finance",
	DnaIcon: "Health & Wellness",
	DogIcon: "Weather & Nature",
	DoorIcon: "Commerce",
	DoorOpenIcon: "Commerce",
	DotIcon: "System & Devices",
	DotOutlineIcon: "System & Devices",
	DotsNineIcon: "System & Devices",
	DotsSixIcon: "System & Devices",
	DotsSixVerticalIcon: "System & Devices",
	DotsThreeCircleIcon: "System & Devices",
	DotsThreeCircleVerticalIcon: "System & Devices",
	DotsThreeIcon: "System & Devices",
	DotsThreeOutlineIcon: "System & Devices",
	DotsThreeOutlineVerticalIcon: "System & Devices",
	DotsThreeVerticalIcon: "System & Devices",
	DownloadIcon: "System & Devices",
	DownloadSimpleIcon: "System & Devices",
	DresserIcon: "Commerce",
	DressIcon: "Commerce",
	DribbbleLogoIcon: "Brands",
	DroneIcon: "Games",
	DropboxLogoIcon: "Brands",
	DropHalfBottomIcon: "Design",
	DropHalfIcon: "Design",
	DropIcon: "Weather & Nature",
	DropSimpleIcon: "Weather & Nature",
	DropSlashIcon: "Design",
	DumpTruckIcon: "AutoGuru",
	EarIcon: "Media",
	EarSlashIcon: "Media",
	EggCrackIcon: "Commerce",
	EggIcon: "Commerce",
	EjectIcon: "Media",
	EjectSimpleIcon: "Media",
	ElevatorIcon: "Maps & Travel",
	EmptyIcon: "Math & Finance",
	EngineIcon: "Maps & Travel",
	EngineOffIcon: "AutoGuru",
	EnvelopeIcon: "Communication",
	EnvelopeOpenIcon: "Communication",
	EnvelopeSimpleIcon: "Communication",
	EnvelopeSimpleOpenIcon: "Communication",
	EqualizerIcon: "Media",
	EqualsIcon: "Math & Finance",
	EraserIcon: "Design",
	EscalatorDownIcon: "Maps & Travel",
	EscalatorUpIcon: "Maps & Travel",
	EvHybridIcon: "AutoGuru",
	ExamIcon: "Education",
	ExclamationMarkIcon: "Security & Warnings",
	ExcludeIcon: "Design",
	ExcludeSquareIcon: "Design",
	ExportIcon: "Communication",
	EyeClosedIcon: "Design",
	EyedropperIcon: "Design",
	EyedropperSampleIcon: "Design",
	EyeglassesIcon: "Commerce",
	EyeIcon: "Design",
	EyesIcon: "People",
	EyeSlashIcon: "Design",
	FacebookBoxIcon: "Brands",
	FacebookLogoIcon: "Brands",
	FaceMaskIcon: "Health & Wellness",
	FactoryIcon: "Commerce",
	FadersHorizontalIcon: "Media",
	FadersIcon: "Media",
	FalloutShelterIcon: "Security & Warnings",
	FanIcon: "Commerce",
	FarmIcon: "Commerce",
	FastForwardCircleIcon: "Media",
	FastForwardIcon: "Media",
	FeatherIcon: "Weather & Nature",
	FediverseLogoIcon: "Brands",
	FgPlateIcon: "AutoGuru",
	FigmaLogoIcon: "Brands",
	FileArchiveIcon: "Office & Editing",
	FileArrowDownIcon: "Office & Editing",
	FileArrowUpIcon: "Office & Editing",
	FileAudioIcon: "Office & Editing",
	FileCIcon: "Office & Editing",
	FileCloudIcon: "Office & Editing",
	FileCodeIcon: "Office & Editing",
	FileCppIcon: "Office & Editing",
	FileCSharpIcon: "Office & Editing",
	FileCssIcon: "Office & Editing",
	FileCsvIcon: "Office & Editing",
	FileDashedIcon: "Office & Editing",
	FileDocIcon: "Office & Editing",
	FileHtmlIcon: "Office & Editing",
	FileIcon: "Office & Editing",
	FileImageIcon: "Office & Editing",
	FileIniIcon: "Office & Editing",
	FileJpgIcon: "Office & Editing",
	FileJsIcon: "Office & Editing",
	FileJsxIcon: "Office & Editing",
	FileLockIcon: "Office & Editing",
	FileMagnifyingGlassIcon: "Office & Editing",
	FileMdIcon: "Office & Editing",
	FileMinusIcon: "Office & Editing",
	FilePdfIcon: "Office & Editing",
	FilePlusIcon: "Office & Editing",
	FilePngIcon: "Office & Editing",
	FilePptIcon: "Office & Editing",
	FilePyIcon: "Office & Editing",
	FileRsIcon: "Office & Editing",
	FilesIcon: "Office & Editing",
	FileSqlIcon: "Office & Editing",
	FileSvgIcon: "Office & Editing",
	FileTextIcon: "Office & Editing",
	FileTsIcon: "Office & Editing",
	FileTsxIcon: "Office & Editing",
	FileTxtIcon: "Office & Editing",
	FileVideoIcon: "Office & Editing",
	FileVueIcon: "Office & Editing",
	FileXIcon: "Office & Editing",
	FileXlsIcon: "Office & Editing",
	FileZipIcon: "Office & Editing",
	FilmReelIcon: "Media",
	FilmScriptIcon: "Media",
	FilmSlateIcon: "Media",
	FilmStripIcon: "Media",
	FingerprintIcon: "Security & Warnings",
	FingerprintSimpleIcon: "Security & Warnings",
	FinnTheHumanIcon: "Games",
	FireExtinguisherIcon: "Security & Warnings",
	FireIcon: "Weather & Nature",
	FireSimpleIcon: "Weather & Nature",
	FireTruckIcon: "Health & Wellness",
	FirstAidIcon: "Health & Wellness",
	FirstAidKitIcon: "Health & Wellness",
	FishIcon: "Weather & Nature",
	FishSimpleIcon: "Weather & Nature",
	FlagBannerFoldIcon: "Maps & Travel",
	FlagBannerIcon: "Maps & Travel",
	FlagCheckeredIcon: "Maps & Travel",
	FlagIcon: "Maps & Travel",
	FlagPennantIcon: "Maps & Travel",
	FlameIcon: "Weather & Nature",
	FlashlightIcon: "System & Devices",
	FlaskIcon: "Health & Wellness",
	FlipHorizontalIcon: "Design",
	FlipVerticalIcon: "Design",
	FloppyDiskBackIcon: "Office & Editing",
	FloppyDiskIcon: "Office & Editing",
	FlowArrowIcon: "Design",
	FlowerIcon: "Weather & Nature",
	FlowerLotusIcon: "Weather & Nature",
	FlowerTulipIcon: "Weather & Nature",
	FlyingSaucerIcon: "Games",
	FolderDashedIcon: "Office & Editing",
	FolderIcon: "Office & Editing",
	FolderLockIcon: "Office & Editing",
	FolderMinusIcon: "Office & Editing",
	FolderOpenIcon: "Office & Editing",
	FolderPlusIcon: "Office & Editing",
	FoldersIcon: "Office & Editing",
	FolderSimpleDashedIcon: "Office & Editing",
	FolderSimpleIcon: "Office & Editing",
	FolderSimpleLockIcon: "Office & Editing",
	FolderSimpleMinusIcon: "Office & Editing",
	FolderSimplePlusIcon: "Office & Editing",
	FolderSimpleStarIcon: "Office & Editing",
	FolderSimpleUserIcon: "Office & Editing",
	FolderStarIcon: "Office & Editing",
	FolderUserIcon: "Office & Editing",
	FootballHelmetIcon: "Games",
	FootballIcon: "Games",
	FootprintsIcon: "People",
	ForkKnifeIcon: "Commerce",
	ForkliftIcon: "AutoGuru",
	FourByFourIcon: "AutoGuru",
	FourKIcon: "Media",
	FrameCornersIcon: "Media",
	FramerLogoIcon: "Brands",
	FuelYesIcon: "AutoGuru",
	FunctionIcon: "Math & Finance",
	FunnelIcon: "Office & Editing",
	FunnelSimpleIcon: "Office & Editing",
	FunnelSimpleXIcon: "Office & Editing",
	FunnelXIcon: "Office & Editing",
	GameControllerIcon: "Games",
	GarageIcon: "Commerce",
	GasCanIcon: "Maps & Travel",
	GasPumpIcon: "Maps & Travel",
	GaugeIcon: "System & Devices",
	GavelIcon: "Commerce",
	GearFineIcon: "Design",
	GearIcon: "System & Devices",
	GearSixIcon: "System & Devices",
	GenderFemaleIcon: "People",
	GenderIntersexIcon: "People",
	GenderMaleIcon: "People",
	GenderNeuterIcon: "People",
	GenderNonbinaryIcon: "People",
	GenderTransgenderIcon: "People",
	GhostIcon: "Games",
	GifIcon: "Media",
	GiftIcon: "Commerce",
	GitBranchIcon: "Development",
	GitCommitIcon: "Development",
	GitDiffIcon: "Development",
	GitForkIcon: "Development",
	GithubLogoIcon: "Brands",
	GitlabLogoIcon: "Brands",
	GitlabLogoSimpleIcon: "Brands",
	GitMergeIcon: "Development",
	GitPullRequestIcon: "Development",
	GlobeHemisphereEastIcon: "Maps & Travel",
	GlobeHemisphereWestIcon: "Maps & Travel",
	GlobeIcon: "Maps & Travel",
	GlobeSimpleIcon: "Maps & Travel",
	GlobeSimpleXIcon: "Maps & Travel",
	GlobeStandIcon: "Maps & Travel",
	GlobeXIcon: "Maps & Travel",
	GogglesIcon: "Maps & Travel",
	GolfCartIcon: "AutoGuru",
	GolfIcon: "Games",
	GoodreadsLogoIcon: "Brands",
	GoogleCardboardLogoIcon: "Games",
	GoogleChromeLogoIcon: "Brands",
	GoogleDriveLogoIcon: "Brands",
	GoogleLogoIcon: "Brands",
	GooglePhotosLogoIcon: "Brands",
	GooglePlayLogoIcon: "Brands",
	GooglePodcastsLogoIcon: "Brands",
	GpsFixIcon: "Maps & Travel",
	GpsIcon: "Maps & Travel",
	GpsSlashIcon: "Maps & Travel",
	GradientIcon: "Design",
	GraduationCapIcon: "Education",
	GrainsIcon: "Commerce",
	GrainsSlashIcon: "Commerce",
	GraphIcon: "Math & Finance",
	GraphicsCardIcon: "Development",
	GreaterThanIcon: "Math & Finance",
	GreaterThanOrEqualIcon: "Math & Finance",
	GridFourIcon: "Design",
	GridNineIcon: "Design",
	GuitarIcon: "Media",
	HairDryerIcon: "Commerce",
	HamburgerIcon: "Commerce",
	HammerIcon: "Commerce",
	HandArrowDownIcon: "People",
	HandArrowUpIcon: "People",
	HandbagIcon: "Commerce",
	HandbagSimpleIcon: "Commerce",
	HandCoinsIcon: "Commerce",
	HandDepositIcon: "People",
	HandEyeIcon: "People",
	HandFistIcon: "People",
	HandGrabbingIcon: "People",
	HandHeartIcon: "Health & Wellness",
	HandIcon: "People",
	HandPalmIcon: "People",
	HandPeaceIcon: "People",
	HandPointingIcon: "People",
	HandsClappingIcon: "People",
	HandshakeIcon: "People",
	HandSoapIcon: "Health & Wellness",
	HandsPrayingIcon: "People",
	HandSwipeLeftIcon: "System & Devices",
	HandSwipeRightIcon: "System & Devices",
	HandTapIcon: "System & Devices",
	HandWavingIcon: "People",
	HandWithdrawIcon: "People",
	HardDriveIcon: "System & Devices",
	HardDrivesIcon: "System & Devices",
	HardHatIcon: "Commerce",
	HashIcon: "Communication",
	HashStraightIcon: "Communication",
	HeadCircuitIcon: "Development",
	HeadlightsIcon: "Maps & Travel",
	HeadphonesIcon: "Media",
	HeadsetIcon: "Media",
	HeartbeatIcon: "Health & Wellness",
	HeartBreakIcon: "Games",
	HeartFilledIcon: "Filled",
	HeartHalfIcon: "Games",
	HeartIcon: "Games",
	HeartStraightBreakIcon: "Games",
	HeartStraightIcon: "Games",
	HexagonIcon: "Design",
	HighDefinitionIcon: "Media",
	HighHeelIcon: "Commerce",
	HighlighterCircleIcon: "Design",
	HighlighterIcon: "Design",
	HockeyIcon: "Games",
	HoodieIcon: "Commerce",
	HorseIcon: "Games",
	HospitalIcon: "Maps & Travel",
	HourglassHighIcon: "Time",
	HourglassIcon: "Time",
	HourglassLowIcon: "Time",
	HourglassMediumIcon: "Time",
	HourglassSimpleHighIcon: "Time",
	HourglassSimpleIcon: "Time",
	HourglassSimpleLowIcon: "Time",
	HourglassSimpleMediumIcon: "Time",
	HouseIcon: "Maps & Travel",
	HouseLineIcon: "Maps & Travel",
	HouseSimpleIcon: "Maps & Travel",
	HurricaneIcon: "Weather & Nature",
	IceCreamIcon: "Commerce",
	IdentificationBadgeIcon: "People",
	IdentificationCardIcon: "People",
	ImageBrokenIcon: "Media",
	ImageIcon: "Media",
	ImagesIcon: "Media",
	ImageSquareIcon: "Media",
	ImagesSquareIcon: "Media",
	InfinityIcon: "Math & Finance",
	InfoIcon: "Security & Warnings",
	InformationIcon: "Filled",
	InstagramFilledIcon: "Filled",
	InstagramIcon: "Brands",
	InstagramLogoIcon: "Brands",
	IntersectIcon: "Design",
	IntersectionIcon: "Math & Finance",
	IntersectSquareIcon: "Design",
	IntersectThreeIcon: "Design",
	InvoiceIcon: "Commerce",
	IslandIcon: "Weather & Nature",
	JarIcon: "Commerce",
	JarLabelIcon: "Commerce",
	JeepIcon: "Maps & Travel",
	JoystickIcon: "Games",
	KanbanIcon: "Office & Editing",
	KeyboardIcon: "System & Devices",
	KeyholeIcon: "Security & Warnings",
	KeyIcon: "Security & Warnings",
	KeyReturnIcon: "System & Devices",
	KnifeIcon: "Commerce",
	LadderIcon: "Commerce",
	LadderSimpleIcon: "Commerce",
	LampIcon: "Commerce",
	LampPendantIcon: "Commerce",
	LaptopIcon: "System & Devices",
	LassoIcon: "Design",
	LastfmLogoIcon: "Brands",
	LayoutIcon: "Design",
	LeafIcon: "Weather & Nature",
	LearnerIcon: "AutoGuru",
	LecternIcon: "Education",
	LegoIcon: "Games",
	LegoSmileyIcon: "Games",
	LessThanIcon: "Math & Finance",
	LessThanOrEqualIcon: "Math & Finance",
	LetterCircleHIcon: "Communication",
	LetterCirclePIcon: "Communication",
	LetterCircleVIcon: "Communication",
	LifebuoyIcon: "Health & Wellness",
	LightbulbFilamentIcon: "System & Devices",
	LightbulbIcon: "System & Devices",
	LighthouseIcon: "Maps & Travel",
	LightningAIcon: "System & Devices",
	LightningIcon: "System & Devices",
	LightningSlashIcon: "System & Devices",
	LineSegmentIcon: "Design",
	LineSegmentsIcon: "Design",
	LineVerticalIcon: "Design",
	LinkBreakIcon: "System & Devices",
	LinkedinBoxIcon: "Brands",
	LinkedinLogoIcon: "Brands",
	LinkIcon: "System & Devices",
	LinkSimpleBreakIcon: "System & Devices",
	LinkSimpleHorizontalBreakIcon: "System & Devices",
	LinkSimpleHorizontalIcon: "System & Devices",
	LinkSimpleIcon: "System & Devices",
	LinktreeLogoIcon: "Brands",
	LinuxLogoIcon: "Brands",
	ListBulletsIcon: "Office & Editing",
	ListChecksIcon: "Office & Editing",
	ListDashesIcon: "Office & Editing",
	ListHeartIcon: "System & Devices",
	ListIcon: "Office & Editing",
	ListMagnifyingGlassIcon: "System & Devices",
	ListNumbersIcon: "Office & Editing",
	ListPlusIcon: "Office & Editing",
	ListStarIcon: "System & Devices",
	LockersIcon: "Maps & Travel",
	LockIcon: "Security & Warnings",
	LockKeyIcon: "Security & Warnings",
	LockKeyOpenIcon: "Security & Warnings",
	LockLaminatedIcon: "Security & Warnings",
	LockLaminatedOpenIcon: "Security & Warnings",
	LockOpenIcon: "Security & Warnings",
	LockSimpleIcon: "Security & Warnings",
	LockSimpleOpenIcon: "Security & Warnings",
	LogIcon: "Weather & Nature",
	LpgIcon: "AutoGuru",
	MagicWandIcon: "Design",
	MagnetIcon: "Development",
	MagnetStraightIcon: "Development",
	MagnifyingGlassIcon: "System & Devices",
	MagnifyingGlassMinusIcon: "System & Devices",
	MagnifyingGlassPlusIcon: "System & Devices",
	MailboxIcon: "Communication",
	MapPinAreaIcon: "Maps & Travel",
	MapPinIcon: "Maps & Travel",
	MapPinLineIcon: "Maps & Travel",
	MapPinPlusIcon: "Maps & Travel",
	MapPinSimpleAreaIcon: "Maps & Travel",
	MapPinSimpleIcon: "Maps & Travel",
	MapPinSimpleLineIcon: "Maps & Travel",
	MapTrifoldIcon: "Maps & Travel",
	MarkdownLogoIcon: "Development",
	MarkerCircleIcon: "Design",
	MartiniIcon: "Commerce",
	MaskHappyIcon: "Games",
	MaskSadIcon: "Games",
	MastodonLogoIcon: "Brands",
	MathOperationsIcon: "Math & Finance",
	MatrixLogoIcon: "Communication",
	MedalIcon: "Games",
	MedalMilitaryIcon: "Games",
	MediumLogoIcon: "Brands",
	MegaphoneIcon: "Communication",
	MegaphoneSimpleIcon: "Communication",
	MemberOfIcon: "Math & Finance",
	MemoryIcon: "System & Devices",
	MessengerLogoIcon: "Brands",
	MetaLogoIcon: "Brands",
	MeteorIcon: "Weather & Nature",
	MetronomeIcon: "Media",
	MicrophoneIcon: "Media",
	MicrophoneSlashIcon: "Media",
	MicrophoneStageIcon: "Media",
	MicroscopeIcon: "Health & Wellness",
	MicrosoftExcelLogoIcon: "Brands",
	MicrosoftOutlookLogoIcon: "Brands",
	MicrosoftPowerpointLogoIcon: "Brands",
	MicrosoftTeamsLogoIcon: "Brands",
	MicrosoftWordLogoIcon: "Brands",
	MinusCircleIcon: "Math & Finance",
	MinusIcon: "Math & Finance",
	MinusSquareIcon: "Math & Finance",
	MobileMechanicIcon: "AutoGuru",
	MoneyIcon: "Commerce",
	MoneyWavyIcon: "Commerce",
	MonitorArrowUpIcon: "System & Devices",
	MonitorIcon: "System & Devices",
	MonitorPlayIcon: "System & Devices",
	MoonIcon: "Weather & Nature",
	MoonStarsIcon: "Weather & Nature",
	MopedFrontIcon: "Maps & Travel",
	MopedIcon: "Maps & Travel",
	MosqueIcon: "Maps & Travel",
	MotorcycleIcon: "Maps & Travel",
	MountainsIcon: "Weather & Nature",
	MouseIcon: "System & Devices",
	MouseLeftClickIcon: "System & Devices",
	MouseMiddleClickIcon: "System & Devices",
	MouseRightClickIcon: "System & Devices",
	MouseScrollIcon: "System & Devices",
	MouseSimpleIcon: "System & Devices",
	MufflerIcon: "AutoGuru",
	MusicNoteIcon: "Media",
	MusicNotesIcon: "Media",
	MusicNoteSimpleIcon: "Media",
	MusicNotesMinusIcon: "Media",
	MusicNotesPlusIcon: "Media",
	MusicNotesSimpleIcon: "Media",
	NavigationArrowIcon: "Maps & Travel",
	NeedleIcon: "Commerce",
	NetworkIcon: "System & Devices",
	NetworkSlashIcon: "System & Devices",
	NetworkXIcon: "System & Devices",
	NewspaperClippingIcon: "Media",
	NewspaperIcon: "Media",
	NotchesIcon: "Design",
	NoteBlankIcon: "Office & Editing",
	NotebookIcon: "Office & Editing",
	NoteIcon: "Office & Editing",
	NotepadIcon: "Office & Editing",
	NotePencilIcon: "Office & Editing",
	NotEqualsIcon: "Math & Finance",
	NotificationIcon: "System & Devices",
	NotionLogoIcon: "Brands",
	NotMemberOfIcon: "Math & Finance",
	NotSubsetOfIcon: "Math & Finance",
	NotSupersetOfIcon: "Math & Finance",
	NuclearPlantIcon: "Commerce",
	NumberCircleEightIcon: "Math & Finance",
	NumberCircleFiveIcon: "Math & Finance",
	NumberCircleFourIcon: "Math & Finance",
	NumberCircleNineIcon: "Math & Finance",
	NumberCircleOneIcon: "Math & Finance",
	NumberCircleSevenIcon: "Math & Finance",
	NumberCircleSixIcon: "Math & Finance",
	NumberCircleThreeIcon: "Math & Finance",
	NumberCircleTwoIcon: "Math & Finance",
	NumberCircleZeroIcon: "Math & Finance",
	NumberEightIcon: "Math & Finance",
	NumberFiveIcon: "Math & Finance",
	NumberFourIcon: "Math & Finance",
	NumberNineIcon: "Math & Finance",
	NumberOneIcon: "Math & Finance",
	NumberSevenIcon: "Math & Finance",
	NumberSixIcon: "Math & Finance",
	NumberSquareEightIcon: "Math & Finance",
	NumberSquareFiveIcon: "Math & Finance",
	NumberSquareFourIcon: "Math & Finance",
	NumberSquareNineIcon: "Math & Finance",
	NumberSquareOneIcon: "Math & Finance",
	NumberSquareSevenIcon: "Math & Finance",
	NumberSquareSixIcon: "Math & Finance",
	NumberSquareThreeIcon: "Math & Finance",
	NumberSquareTwoIcon: "Math & Finance",
	NumberSquareZeroIcon: "Math & Finance",
	NumberThreeIcon: "Math & Finance",
	NumberTwoIcon: "Math & Finance",
	NumberZeroIcon: "Math & Finance",
	NumpadIcon: "Communication",
	NutIcon: "System & Devices",
	NyTimesLogoIcon: "Brands",
	OctagonIcon: "Design",
	OfficeChairIcon: "Commerce",
	OnigiriIcon: "Commerce",
	OpenAiLogoIcon: "Brands",
	OptionIcon: "System & Devices",
	OrangeIcon: "Commerce",
	OrangeSliceIcon: "Commerce",
	OttoIcon: "AutoGuru",
	OvenIcon: "Commerce",
	PackageIcon: "Commerce",
	PaintBrushBroadIcon: "Design",
	PaintBrushHouseholdIcon: "Design",
	PaintBrushIcon: "Design",
	PaintBucketIcon: "Design",
	PaintRollerIcon: "Design",
	PaletteIcon: "Design",
	PanoramaIcon: "Media",
	PantsIcon: "Commerce",
	PaperclipHorizontalIcon: "Office & Editing",
	PaperclipIcon: "Office & Editing",
	PaperPlaneIcon: "Communication",
	PaperPlaneRightIcon: "Communication",
	PaperPlaneTiltIcon: "Communication",
	ParachuteIcon: "Games",
	ParagraphIcon: "Office & Editing",
	ParallelogramIcon: "Design",
	ParkIcon: "Maps & Travel",
	ParkingIcon: "AutoGuru",
	PasswordIcon: "Security & Warnings",
	PathIcon: "Maps & Travel",
	PatreonLogoIcon: "Brands",
	PauseCircleIcon: "Media",
	PauseIcon: "Media",
	PawPrintIcon: "Weather & Nature",
	PaypalLogoIcon: "Brands",
	PeaceIcon: "Communication",
	PencilCircleIcon: "Design",
	PencilIcon: "Design",
	PencilLineIcon: "Design",
	PencilRulerIcon: "Design",
	PencilSimpleIcon: "Design",
	PencilSimpleLineIcon: "Design",
	PencilSimpleSlashIcon: "Design",
	PencilSlashIcon: "Design",
	PenIcon: "Design",
	PenNibIcon: "Design",
	PenNibStraightIcon: "Design",
	PentagonIcon: "Design",
	PentagramIcon: "Design",
	PepperIcon: "Commerce",
	PercentIcon: "Math & Finance",
	PersonArmsSpreadIcon: "People",
	PersonIcon: "People",
	PersonSimpleBikeIcon: "People",
	PersonSimpleCircleIcon: "People",
	PersonSimpleHikeIcon: "People",
	PersonSimpleIcon: "People",
	PersonSimpleRunIcon: "People",
	PersonSimpleSkiIcon: "Games",
	PersonSimpleSnowboardIcon: "Games",
	PersonSimpleSwimIcon: "People",
	PersonSimpleTaiChiIcon: "People",
	PersonSimpleThrowIcon: "People",
	PersonSimpleWalkIcon: "People",
	PerspectiveIcon: "Design",
	PhoneCallIcon: "Communication",
	PhoneDisconnectIcon: "Communication",
	PhoneIcon: "Communication",
	PhoneIncomingIcon: "Communication",
	PhoneListIcon: "Communication",
	PhoneOutgoingIcon: "Communication",
	PhonePauseIcon: "Communication",
	PhonePlusIcon: "Communication",
	PhoneSlashIcon: "Communication",
	PhoneTransferIcon: "Communication",
	PhoneXIcon: "Communication",
	PhosphorLogoIcon: "Brands",
	PianoKeysIcon: "Media",
	PicnicTableIcon: "Commerce",
	PictureInPictureIcon: "Media",
	PiggyBankIcon: "Commerce",
	PiIcon: "Math & Finance",
	PillIcon: "Health & Wellness",
	PingPongIcon: "Games",
	PinterestLogoIcon: "Brands",
	PintGlassIcon: "Commerce",
	PinwheelIcon: "Games",
	PipeIcon: "Commerce",
	PipeWrenchIcon: "Commerce",
	PixLogoIcon: "Commerce",
	PizzaIcon: "Commerce",
	PlaceholderIcon: "Design",
	PlanetIcon: "Weather & Nature",
	PlantIcon: "Weather & Nature",
	PlateIcon: "AutoGuru",
	PlayCircleIcon: "Media",
	PlayIcon: "Media",
	PlaylistIcon: "Media",
	PlayPauseIcon: "Media",
	PlugChargingIcon: "System & Devices",
	PlugIcon: "System & Devices",
	PlugsConnectedIcon: "System & Devices",
	PlugsIcon: "System & Devices",
	PlusCircleIcon: "Math & Finance",
	PlusIcon: "Math & Finance",
	PlusMinusIcon: "Math & Finance",
	PlusSquareIcon: "Math & Finance",
	PokerChipIcon: "Games",
	PoliceCarIcon: "Maps & Travel",
	PolygonIcon: "Design",
	PopcornIcon: "Commerce",
	PopsicleIcon: "Commerce",
	PottedPlantIcon: "Commerce",
	PowerIcon: "System & Devices",
	PPlateIcon: "AutoGuru",
	PrescriptionIcon: "Health & Wellness",
	PresentationChartIcon: "Office & Editing",
	PresentationIcon: "Office & Editing",
	PrinterIcon: "Office & Editing",
	ProhibitIcon: "Security & Warnings",
	ProhibitInsetIcon: "Security & Warnings",
	ProjectorScreenChartIcon: "Office & Editing",
	ProjectorScreenIcon: "Office & Editing",
	PulseIcon: "Health & Wellness",
	PushPinIcon: "Office & Editing",
	PushPinSimpleIcon: "Office & Editing",
	PushPinSimpleSlashIcon: "Office & Editing",
	PushPinSlashIcon: "Office & Editing",
	PuzzlePieceIcon: "Games",
	QrCodeIcon: "System & Devices",
	QuestionIcon: "Security & Warnings",
	QuestionMarkIcon: "Security & Warnings",
	QueueIcon: "Media",
	QuoteRequestIcon: "AutoGuru",
	QuotesIcon: "Communication",
	RabbitIcon: "Weather & Nature",
	RacquetIcon: "Games",
	RadicalIcon: "Math & Finance",
	RadioactiveIcon: "Security & Warnings",
	RadioButtonIcon: "System & Devices",
	RadioIcon: "Communication",
	RainbowCloudIcon: "Weather & Nature",
	RainbowIcon: "Weather & Nature",
	RankingIcon: "Games",
	ReadCvLogoIcon: "Brands",
	ReceiptIcon: "Commerce",
	ReceiptXIcon: "Commerce",
	RecordIcon: "Media",
	RectangleDashedIcon: "Design",
	RectangleIcon: "Design",
	RecycleIcon: "Arrows",
	RedditLogoIcon: "Brands",
	RepeatIcon: "Media",
	RepeatOnceIcon: "Media",
	ReplitLogoIcon: "Brands",
	ResizeIcon: "Design",
	RewindCircleIcon: "Media",
	RewindIcon: "Media",
	RoadHorizonIcon: "Maps & Travel",
	RobotIcon: "Development",
	RocketIcon: "Maps & Travel",
	RocketLaunchIcon: "Maps & Travel",
	RowsIcon: "Design",
	RowsPlusBottomIcon: "Design",
	RowsPlusTopIcon: "Design",
	RssIcon: "Communication",
	RssSimpleIcon: "Communication",
	RugIcon: "Commerce",
	RulerIcon: "Design",
	SailboatIcon: "Maps & Travel",
	ScalesIcon: "Commerce",
	ScanIcon: "System & Devices",
	ScanSmileyIcon: "System & Devices",
	ScissorsIcon: "Design",
	ScooterIcon: "Maps & Travel",
	ScreencastIcon: "Media",
	ScrewdriverIcon: "Commerce",
	ScribbleIcon: "Design",
	ScribbleLoopIcon: "Design",
	ScrollIcon: "Games",
	SealCheckIcon: "Security & Warnings",
	SealIcon: "Security & Warnings",
	SealPercentIcon: "Security & Warnings",
	SealQuestionIcon: "Security & Warnings",
	SealWarningIcon: "Security & Warnings",
	SeatbeltIcon: "Commerce",
	SeatIcon: "Maps & Travel",
	SecurityCameraIcon: "Security & Warnings",
	SelectionAllIcon: "Design",
	SelectionBackgroundIcon: "Design",
	SelectionForegroundIcon: "Design",
	SelectionIcon: "Design",
	SelectionInverseIcon: "Design",
	SelectionPlusIcon: "Design",
	SelectionSlashIcon: "Design",
	ShapesIcon: "Design",
	ShareFatIcon: "Communication",
	ShareIcon: "Communication",
	ShareNetworkIcon: "Communication",
	ShieldCheckeredIcon: "Security & Warnings",
	ShieldCheckIcon: "Security & Warnings",
	ShieldChevronIcon: "Security & Warnings",
	ShieldIcon: "Security & Warnings",
	ShieldPlusIcon: "Security & Warnings",
	ShieldSlashIcon: "Security & Warnings",
	ShieldStarIcon: "Security & Warnings",
	ShieldWarningIcon: "Security & Warnings",
	ShippingContainerIcon: "Maps & Travel",
	ShirtFoldedIcon: "Commerce",
	ShootingStarIcon: "Weather & Nature",
	ShoppingBagIcon: "Commerce",
	ShoppingBagOpenIcon: "Commerce",
	ShoppingCartIcon: "Commerce",
	ShoppingCartSimpleIcon: "Commerce",
	ShovelIcon: "Commerce",
	ShowerIcon: "Commerce",
	ShrimpIcon: "Weather & Nature",
	ShuffleAngularIcon: "Media",
	ShuffleIcon: "Media",
	ShuffleSimpleIcon: "Media",
	SidebarIcon: "Design",
	SidebarSimpleIcon: "Design",
	SigmaIcon: "Math & Finance",
	SignatureIcon: "Communication",
	SignInIcon: "System & Devices",
	SignOutIcon: "System & Devices",
	SignpostIcon: "Maps & Travel",
	SimCardIcon: "System & Devices",
	SirenIcon: "Security & Warnings",
	SketchLogoIcon: "Brands",
	SkipBackCircleIcon: "Media",
	SkipBackIcon: "Media",
	SkipForwardCircleIcon: "Media",
	SkipForwardIcon: "Media",
	SkullIcon: "Games",
	SkypeLogoIcon: "Brands",
	SlackLogoIcon: "Brands",
	SlidersHorizontalIcon: "Media",
	SlidersIcon: "Media",
	SlideshowIcon: "Media",
	SmileyAngryIcon: "People",
	SmileyBlankIcon: "People",
	SmileyIcon: "People",
	SmileyMehIcon: "People",
	SmileyMeltingIcon: "People",
	SmileyNervousIcon: "People",
	SmileySadIcon: "People",
	SmileyStickerIcon: "People",
	SmileyWinkIcon: "People",
	SmileyXEyesIcon: "People",
	SnapchatLogoIcon: "Brands",
	SneakerIcon: "Commerce",
	SneakerMoveIcon: "Commerce",
	SnowflakeIcon: "Weather & Nature",
	SoccerBallIcon: "Games",
	SockIcon: "Commerce",
	SolarPanelIcon: "Commerce",
	SolarRoofIcon: "Commerce",
	SortAscendingIcon: "Office & Editing",
	SortDescendingIcon: "Office & Editing",
	SoundcloudLogoIcon: "Brands",
	SpadeIcon: "Games",
	SparkleIcon: "Weather & Nature",
	SpeakerHifiIcon: "Media",
	SpeakerHighIcon: "Media",
	SpeakerLowIcon: "Media",
	SpeakerNoneIcon: "Media",
	SpeakerSimpleHighIcon: "Media",
	SpeakerSimpleLowIcon: "Media",
	SpeakerSimpleNoneIcon: "Media",
	SpeakerSimpleSlashIcon: "Media",
	SpeakerSimpleXIcon: "Media",
	SpeakerSlashIcon: "Media",
	SpeakerXIcon: "Media",
	SpeedometerIcon: "System & Devices",
	SphereIcon: "Design",
	SpinnerBallIcon: "System & Devices",
	SpinnerGapIcon: "System & Devices",
	SpinnerIcon: "System & Devices",
	SpiralIcon: "Games",
	SplitHorizontalIcon: "Design",
	SplitVerticalIcon: "Design",
	SpotifyLogoIcon: "Brands",
	SprayBottleIcon: "Design",
	SquareHalfBottomIcon: "Design",
	SquareHalfIcon: "Design",
	SquareIcon: "Design",
	SquareLogoIcon: "Brands",
	SquaresFourIcon: "Design",
	SquareSplitHorizontalIcon: "Design",
	SquareSplitVerticalIcon: "Design",
	StackIcon: "Design",
	StackMinusIcon: "Design",
	StackOverflowLogoIcon: "Brands",
	StackPlusIcon: "Design",
	StackSimpleIcon: "Design",
	StairsIcon: "Commerce",
	StampIcon: "Design",
	StandardDefinitionIcon: "Media",
	StarAndCrescentIcon: "Communication",
	StarFilledIcon: "Filled",
	StarFourIcon: "Weather & Nature",
	StarHalfIcon: "Filled",
	StarIcon: "Filled",
	StarOfDavidIcon: "Communication",
	SteamLogoIcon: "Brands",
	SteeringWheelIcon: "Maps & Travel",
	StepsIcon: "Maps & Travel",
	StethoscopeIcon: "Health & Wellness",
	StickerIcon: "Communication",
	StoolIcon: "Commerce",
	StopCircleIcon: "Media",
	StopIcon: "Media",
	StorefrontIcon: "Commerce",
	StrategyIcon: "Games",
	StripeLogoIcon: "Brands",
	StudentIcon: "Education",
	SubsetOfIcon: "Math & Finance",
	SubsetProperOfIcon: "Math & Finance",
	SubtitlesIcon: "Media",
	SubtitlesSlashIcon: "Media",
	SubtractIcon: "Design",
	SubtractSquareIcon: "Design",
	SubwayIcon: "Maps & Travel",
	SuitcaseIcon: "Maps & Travel",
	SuitcaseRollingIcon: "Maps & Travel",
	SuitcaseSimpleIcon: "Maps & Travel",
	SunDimIcon: "Weather & Nature",
	SunglassesIcon: "Commerce",
	SunHorizonIcon: "Weather & Nature",
	SunIcon: "Weather & Nature",
	SupersetOfIcon: "Math & Finance",
	SupersetProperOfIcon: "Math & Finance",
	SuspensionIcon: "AutoGuru",
	SwapIcon: "System & Devices",
	SwatchesIcon: "Design",
	SwimmingPoolIcon: "Maps & Travel",
	SwordIcon: "Games",
	SynagogueIcon: "Maps & Travel",
	SyringeIcon: "Health & Wellness",
	TableIcon: "Math & Finance",
	TabsIcon: "System & Devices",
	TagChevronIcon: "Commerce",
	TagIcon: "Commerce",
	TagSimpleIcon: "Commerce",
	TargetIcon: "Games",
	TaxiIcon: "Maps & Travel",
	TeaBagIcon: "Commerce",
	TelegramLogoIcon: "Brands",
	TelevisionIcon: "Media",
	TelevisionSimpleIcon: "Media",
	TennisBallIcon: "Games",
	TentIcon: "Maps & Travel",
	TerminalIcon: "Development",
	TerminalWindowIcon: "Development",
	TestTubeIcon: "Health & Wellness",
	TextAaIcon: "Office & Editing",
	TextAlignCenterIcon: "Office & Editing",
	TextAlignJustifyIcon: "Office & Editing",
	TextAlignLeftIcon: "Office & Editing",
	TextAlignRightIcon: "Office & Editing",
	TextAUnderlineIcon: "Design",
	TextBIcon: "Office & Editing",
	TextboxIcon: "Office & Editing",
	TextColumnsIcon: "Office & Editing",
	TextHFiveIcon: "Office & Editing",
	TextHFourIcon: "Office & Editing",
	TextHIcon: "Office & Editing",
	TextHOneIcon: "Office & Editing",
	TextHSixIcon: "Office & Editing",
	TextHThreeIcon: "Office & Editing",
	TextHTwoIcon: "Office & Editing",
	TextIndentIcon: "Office & Editing",
	TextItalicIcon: "Office & Editing",
	TextOutdentIcon: "Office & Editing",
	TextStrikethroughIcon: "Office & Editing",
	TextSubscriptIcon: "Office & Editing",
	TextSuperscriptIcon: "Office & Editing",
	TextTIcon: "Office & Editing",
	TextTSlashIcon: "Office & Editing",
	TextUnderlineIcon: "Office & Editing",
	ThermometerColdIcon: "Weather & Nature",
	ThermometerHotIcon: "Weather & Nature",
	ThermometerIcon: "Weather & Nature",
	ThermometerSimpleIcon: "Weather & Nature",
	ThreadsLogoIcon: "Brands",
	ThreeDIcon: "Media",
	ThumbsDownIcon: "Communication",
	ThumbsUpIcon: "Communication",
	TicketIcon: "Commerce",
	TidalLogoIcon: "Brands",
	TiktokFilledIcon: "Filled",
	TiktokIcon: "Brands",
	TiktokLogoIcon: "Brands",
	TildeIcon: "Math & Finance",
	TimerIcon: "Time",
	TipiIcon: "Maps & Travel",
	TipJarIcon: "Commerce",
	TireIcon: "Commerce",
	ToggleLeftIcon: "System & Devices",
	ToggleRightIcon: "System & Devices",
	ToiletIcon: "Health & Wellness",
	ToiletPaperIcon: "Health & Wellness",
	ToolboxIcon: "Commerce",
	ToothIcon: "Health & Wellness",
	TornadoIcon: "Weather & Nature",
	ToteIcon: "Commerce",
	ToteSimpleIcon: "Commerce",
	TowelIcon: "Commerce",
	TowTruckIcon: "AutoGuru",
	TractorIcon: "Commerce",
	TrademarkIcon: "Commerce",
	TrademarkRegisteredIcon: "Commerce",
	TrafficConeIcon: "Maps & Travel",
	TrafficSignalIcon: "Maps & Travel",
	TrafficSignIcon: "Maps & Travel",
	TrainIcon: "Maps & Travel",
	TrainRegionalIcon: "Maps & Travel",
	TrainSimpleIcon: "Maps & Travel",
	TramIcon: "Maps & Travel",
	TranslateIcon: "Communication",
	TransmissionIcon: "AutoGuru",
	TrashIcon: "Office & Editing",
	TrashSimpleIcon: "Office & Editing",
	TrayArrowDownIcon: "Office & Editing",
	TrayArrowUpIcon: "Office & Editing",
	TrayIcon: "Office & Editing",
	TreasureChestIcon: "Games",
	TreeEvergreenIcon: "Weather & Nature",
	TreeIcon: "Weather & Nature",
	TreePalmIcon: "Games",
	TreeStructureIcon: "Development",
	TreeViewIcon: "System & Devices",
	TrendDownIcon: "Math & Finance",
	TrendUpIcon: "Math & Finance",
	TriangleDashedIcon: "Design",
	TriangleIcon: "Design",
	TrolleyIcon: "Maps & Travel",
	TrolleySuitcaseIcon: "Maps & Travel",
	TrophyIcon: "Games",
	TruckFastIcon: "AutoGuru",
	TruckIcon: "Maps & Travel",
	TruckTrailerIcon: "Commerce",
	TShirtIcon: "Commerce",
	TumblrLogoIcon: "Brands",
	TwitchLogoIcon: "Brands",
	TwitterLogoIcon: "Brands",
	TyreIcon: "AutoGuru",
	TyreTreadIcon: "AutoGuru",
	UberBoxIcon: "Brands",
	UberBoxWhiteIcon: "Brands",
	UberIcon: "Brands",
	UmbrellaIcon: "Weather & Nature",
	UmbrellaSimpleIcon: "Weather & Nature",
	UnionIcon: "Math & Finance",
	UniteIcon: "Design",
	UniteSquareIcon: "Design",
	UploadIcon: "System & Devices",
	UploadSimpleIcon: "System & Devices",
	UsbIcon: "System & Devices",
	UserCheckIcon: "People",
	UserCircleCheckIcon: "People",
	UserCircleDashedIcon: "People",
	UserCircleGearIcon: "People",
	UserCircleIcon: "People",
	UserCircleMinusIcon: "People",
	UserCirclePlusIcon: "People",
	UserFocusIcon: "People",
	UserGearIcon: "People",
	UserIcon: "People",
	UserListIcon: "People",
	UserMinusIcon: "People",
	UserPlusIcon: "People",
	UserRectangleIcon: "People",
	UsersFourIcon: "People",
	UsersIcon: "People",
	UserSoundIcon: "People",
	UserSquareIcon: "People",
	UsersThreeIcon: "People",
	UserSwitchIcon: "People",
	VanIcon: "Maps & Travel",
	VaultIcon: "Security & Warnings",
	VectorThreeIcon: "Arrows",
	VectorTwoIcon: "Arrows",
	VibrateIcon: "System & Devices",
	VideoCameraIcon: "Media",
	VideoCameraSlashIcon: "Media",
	VideoConferenceIcon: "Media",
	VideoIcon: "Education",
	VignetteIcon: "Design",
	VinylRecordIcon: "Media",
	VirtualRealityIcon: "Games",
	VirusIcon: "Health & Wellness",
	VisorIcon: "Media",
	VoicemailIcon: "Communication",
	VolleyballIcon: "Games",
	WalletIcon: "Commerce",
	WallIcon: "Security & Warnings",
	WarehouseIcon: "Commerce",
	WarningCircleIcon: "Security & Warnings",
	WarningDiamondIcon: "Security & Warnings",
	WarningIcon: "Filled",
	WarningOctagonIcon: "Security & Warnings",
	WashingMachineIcon: "Commerce",
	WatchIcon: "Time",
	WaveformIcon: "Media",
	WaveformSlashIcon: "Media",
	WaveSawtoothIcon: "Media",
	WavesIcon: "Weather & Nature",
	WaveSineIcon: "Media",
	WaveSquareIcon: "Media",
	WaveTriangleIcon: "Media",
	WebcamIcon: "Media",
	WebcamSlashIcon: "Media",
	WebhooksLogoIcon: "Development",
	WechatLogoIcon: "Brands",
	WhatsappLogoIcon: "Brands",
	WheelchairIcon: "People",
	WheelchairMotionIcon: "People",
	WifiHighIcon: "System & Devices",
	WifiLowIcon: "System & Devices",
	WifiMediumIcon: "System & Devices",
	WifiNoneIcon: "System & Devices",
	WifiSlashIcon: "System & Devices",
	WifiXIcon: "System & Devices",
	WindIcon: "Weather & Nature",
	WindmillIcon: "Commerce",
	WindowsLogoIcon: "Brands",
	WineIcon: "Commerce",
	WorkshopIcon: "AutoGuru",
	WrenchIcon: "Commerce",
	XCircleIcon: "Math & Finance",
	XIcon: "Math & Finance",
	XLogoIcon: "Brands",
	XSocialFilledIcon: "Filled",
	XSocialIcon: "Brands",
	XSquareIcon: "Math & Finance",
	YarnIcon: "Commerce",
	YinYangIcon: "Communication",
	YoutubeFilledIcon: "Filled",
	YoutubeIcon: "Brands",
	YoutubeLogoIcon: "Brands",
};
