name: Update Storybook

# This workflow is triggered manually to update the Storybook deployment, auto deployment of Storybook is done by the `release` workflow.
on: workflow_dispatch

jobs:
    release:
        name: Update Storybook
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Get Node version
              id: version
              run:
                  echo "node_version=$(jq -r '.volta.node' package.json)" >>
                  $GITHUB_OUTPUT

            - name: Setup Node ${{ steps.version.outputs.node_version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ steps.version.outputs.node_version }}
                  cache: 'yarn'
                  check-latest: true

            - name: Yarn install
              run: yarn --immutable

            - name: Build storybook artefacts
              run: yarn storybook:build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook-static
