name: Update Storybook

# This workflow is triggered manually to update the Storybook deployment, auto deployment of Storybook is done by the `release` workflow.
on: workflow_dispatch

jobs:
    release:
        name: Update Storybook
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Setup environment
              id: setups
              run: |-
                  echo "::set-output name=yarn_cache::$(yarn cache dir)"
                  echo "::set-output name=node_version::$(jq -r '.volta.node' package.json)"

            - name: Setup Node ${{ steps.setups.outputs.node_version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ steps.setups.outputs.node_version }}
                  check-latest: true

            - name: Yarn cache
              uses: actions/cache@main
              with:
                  path: ${{ steps.setups.outputs.yarn_cache }}
                  key:
                      ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')
                      }}-node-${{ steps.setups.outputs.node_version }}

            - run: yarn --immutable

            - name: Build storybook artefacts
              run: yarn storybook:build
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./storybook-static
