name: CI

on:
    pull_request:
        types: [opened, reopened, ready_for_review, synchronize]
    push:
        branches:
            - main
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    setup:
        name: Setup environment
        runs-on: ubuntu-latest
        outputs:
            node_version: ${{ steps.version.outputs.node_version }}
            has_prerelease: ${{ steps.exists.outputs.pre_exists }}
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Get Node version
              id: version
              run:
                  echo "node_version=$(jq -r '.volta.node' package.json)" >>
                  $GITHUB_OUTPUT

            - name: Check for changeset pre.json
              id: exists
              run: |
                  if [ -f ".changeset/pre.json" ]; then
                    echo "Prerelease found"
                    echo "pre_exists=true" >> $GITHUB_OUTPUT
                  else
                    echo "No prerelease found"
                    echo "pre_exists=false" >> $GITHUB_OUTPUT
                  fi

    test:
        name: Lint & Test
        needs: setup
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Setup Node ${{ needs.setup.outputs.node_version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ needs.setup.outputs.node_version }}
                  cache: 'yarn'

            - name: Yarn install
              run: yarn --immutable

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test --run --coverage

            - uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV }}

    visual_test:
        name: Visual changes
        needs: setup
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Setup Node ${{ needs.setup.outputs.node_version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ needs.setup.outputs.node_version }}
                  cache: 'yarn'

            - name: Yarn install
              run: yarn --immutable

            - name: Chromatic
              if: github.event.pull_request.draft == false
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  onlyChanged: true # enables TurboSnap behaviour
                  autoAcceptChanges: 'main'
                  exitZeroOnChanges: '!(main)'
                  skip: 'changeset-release/**'

            - name: Skip Chromatic
              if: github.event.pull_request.draft == true
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  skip: true
