name: CI

on:
    push:
    pull_request_target:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    test:
        name: Lint & Test
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Setup environment
              id: setups
              run: |-
                  echo "::set-output name=yarn_cache::$(yarn cache dir)"
                  echo "::set-output name=node_version::$(jq -r '.volta.node' package.json)"

            - name: Setup Node ${{ steps.setups.outputs.node_version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ steps.setups.outputs.node_version }}
                  check-latest: true

            - name: Yarn cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.setups.outputs.yarn_cache }}
                  key:
                      ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')
                      }}-node-${{ steps.setups.outputs.node_version }}

            - run: yarn --immutable

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn test --no-cache --ci --coverage

            - uses: codecov/codecov-action@v5
              with:
                  token: ${{ secrets.CODECOV }}

    visual_test:
        name: Visual changes
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Setup environment
              id: setups
              run: |-
                  echo "::set-output name=yarn_cache::$(yarn cache dir)"
                  echo "::set-output name=node_version::$(jq -r '.volta.node' package.json)"

            - name: Setup Node ${{ steps.setups.outputs.node_version }}
              uses: actions/setup-node@main
              with:
                  node-version: ${{ steps.setups.outputs.node_version }}
                  check-latest: true

            - name: Yarn cache
              uses: actions/cache@v4
              with:
                  path: ${{ steps.setups.outputs.yarn_cache }}
                  key:
                      ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock')
                      }}-node-${{ steps.setups.outputs.node_version }}

            - run: yarn --immutable

            - name: Skip Chromatic
              if:
                  github.event_name != 'pull_request' ||
                  github.event.pull_request.draft == true
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  skip: true

            - name: Chromatic
              if:
                  github.event_name == 'pull_request' &&
                  github.event.pull_request.draft == false
              uses: chromaui/action@latest
              with:
                  projectToken: ${{ secrets.CHROMATIC_APP_CODE }}
                  onlyChanged: true # enables TurboSnap behaviour
                  autoAcceptChanges: 'main'
                  exitZeroOnChanges: '!(main)'
                  skip: 'changeset-release/**'
