name: Release

on:
    push:
        branches: [main]

jobs:
    release:
        name: Create Release Pull Request
        runs-on: ubuntu-latest
        env:
            TZ: Australia/Brisbane
            CI: true
        steps:
            - uses: actions/checkout@v6
              with:
                  fetch-depth: 0

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: 'package.json'
                  cache: 'yarn'

            - name: Yarn install
              run: yarn --immutable

            - name: Create Release Pull Request
              uses: changesets/action@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
