name: SonarQube Analysis (TypeScript)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarqube:
    name: Analyze Overdrive with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Usa la misma versión que en tu entorno local

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test --coverage
        env:
          CI: true

      - name: Run SonarQube analysis
        env:
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey="${{ github.event.repository.name }}" \
            -Dsonar.organization="your-organization" \
            -Dsonar.sources=lib \
            -Dsonar.tests=lib \
            -Dsonar.inclusions="**/*.ts,**/*.tsx" \
            -Dsonar.exclusions="**/node_modules/**,**/*.stories.tsx,**/*.test.tsx" \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
